version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-day-2
    ports:
      - 8001:3001
    depends_on:
      - db
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web-day-2
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    container_name: db-day-2
    image: postgres:11.2-alpine
    volume:
      - ./volume:var/lib/postgressql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgresdb
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - 5432:5432 
    restart: always
